export const BUTTON_COLOR = '#F2F2F2'
export const HEADER_COLOR = '#434343'
export const BORDER_COLOR = '#707070'
export const HEADER_TEXT_COLOR = '#FFFFFF'
export const BACKGROUND_COLOR = '#FFFFFF'
export const DIGIT_COLOR = '#000000'
